# Generated by Django 5.2.10 on 2026-02-13 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('seat_number', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('percentage', models.FloatField()),
                ('field_of_study', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('university', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=200)),
                ('form_number', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
