# Generated by Django 5.2.10 on 2026-02-13 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0002_university_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='college',
        ),
        migrations.RemoveField(
            model_name='student',
            name='university',
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الاستمارة')),
                ('application_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('priority', models.IntegerField(default=1, verbose_name='ترتيب الرغبة')),
                ('status', models.CharField(default='قيد المراجعة', max_length=50)),
                ('recommendation_logic', models.TextField(blank=True, null=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addmission_app.program')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='addmission_app.student')),
            ],
        ),
    ]
