# Generated by Django 5.2.10 on 2026-02-13 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0003_remove_student_college_remove_student_university_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accepted_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_students', to='addmission_app.program', verbose_name='التخصص المقبول به'),
        ),
        migrations.AddField(
            model_name='application',
            name='accepted_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_applications', to='addmission_app.university', verbose_name='الجامعة المقبول بها'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('قيد المراجعة', 'قيد المراجعة'), ('تم القبول', 'تم القبول'), ('لم يتم القبول', 'لم يتم القبول')], default='قيد المراجعة', max_length=50),
        ),
    ]
