# Generated by Django 5.2.10 on 2026-02-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0004_application_accepted_program_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='form_number',
            field=models.CharField(max_length=50, verbose_name='رقم الاستمارة'),
        ),
    ]
