# Generated by Django 5.2.10 on 2026-02-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0005_alter_application_form_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='category',
        ),
        migrations.RemoveField(
            model_name='program',
            name='field',
        ),
        migrations.AddField(
            model_name='student',
            name='choice1',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 1'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice10',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 10'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice11',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 11'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice12',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 12'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice13',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 13'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice14',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 14'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice15',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 15'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice16',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 16'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice17',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 17'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice18',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 18'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice19',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 19'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice2',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 2'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice20',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 20'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice3',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 3'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice4',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 4'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice5',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 5'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice6',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 6'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice7',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 7'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice8',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 8'),
        ),
        migrations.AddField(
            model_name='student',
            name='choice9',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='الرغبة 9'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(default='قيد المراجعة', max_length=50, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='student',
            name='field_of_study',
            field=models.CharField(max_length=100, verbose_name='المسار الدراسي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='form_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الاستمارة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(max_length=10, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage',
            field=models.FloatField(verbose_name='النسبة المئوية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='student',
            name='region',
            field=models.CharField(max_length=100, verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='seat_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الجلوس'),
        ),
        migrations.AlterField(
            model_name='university',
            name='region',
            field=models.CharField(max_length=100, verbose_name='المنطقة'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
