# Generated by Django 5.2.10 on 2026-02-15 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0006_remove_program_category_remove_program_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice10',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice11',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice12',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice13',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice14',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice15',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice16',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice17',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice18',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice19',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice20',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice4',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice5',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice6',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice7',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice8',
        ),
        migrations.RemoveField(
            model_name='student',
            name='choice9',
        ),
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='region',
        ),
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AlterField(
            model_name='student',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المسار الدراسي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage',
            field=models.FloatField(default=0.0, verbose_name='النسبة المئوية'),
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='قيد المراجعة', max_length=50, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم')),
                ('choice1', models.CharField(blank=True, max_length=300, null=True)),
                ('choice20', models.CharField(blank=True, max_length=300, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='addmission_app.student')),
            ],
        ),
    ]
