# Generated by Django 5.2.10 on 2026-02-15 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0009_application_choice10_application_choice11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='accepted_university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addmission_app.university', verbose_name='الجامعة المقبول بها'),
        ),
    ]
