# Generated by Django 5.2.10 on 2026-02-16 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0010_application_accepted_university'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'طلب تقديم', 'verbose_name_plural': 'طلبات التقديم'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'تخصص', 'verbose_name_plural': 'التخصصات'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'طالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'جامعة', 'verbose_name_plural': 'الجامعات'},
        ),
        migrations.RemoveField(
            model_name='application',
            name='accepted_university',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice1',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice10',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice11',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice12',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice13',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice14',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice15',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice16',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice17',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice18',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice19',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice2',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice20',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice3',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice4',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice5',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice6',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice7',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice8',
        ),
        migrations.RemoveField(
            model_name='application',
            name='choice9',
        ),
        migrations.AddField(
            model_name='application',
            name='accepted_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addmission_app.program', verbose_name='الرغبة المقبول بها'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(default='قيد المراجعة', max_length=50, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='addmission_app.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم التخصص'),
        ),
        migrations.AlterField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='addmission_app.university', verbose_name='الجامعة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='student',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المساق'),
        ),
        migrations.AlterField(
            model_name='student',
            name='form_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الاستمارة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage',
            field=models.FloatField(default=0.0, verbose_name='النسبة المئوية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='student',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='seat_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الجلوس'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='اسم الجامعة'),
        ),
        migrations.AlterField(
            model_name='university',
            name='region',
            field=models.CharField(max_length=100, verbose_name='المنطقة/الولاية'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(verbose_name='ترتيب الرغبة')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='addmission_app.application', verbose_name='الطلب')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addmission_app.program', verbose_name='التخصص المختار')),
            ],
            options={
                'verbose_name': 'رغبة',
                'verbose_name_plural': 'الرغبات المختارة',
                'ordering': ['priority'],
            },
        ),
    ]
