# Generated by Django 5.2.10 on 2026-02-17 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0011_alter_application_options_alter_program_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('يتم المراجعة', 'يتم المراجعة'), ('تم القبول', 'تم القبول'), ('مرفوض', 'مرفوض')], default='يتم المراجعة', max_length=50, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='form_number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم الاستمارة'),
        ),
    ]
