# Generated by Django 5.2.10 on 2026-03-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0012_alter_application_status_alter_student_form_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='university_type',
            field=models.CharField(choices=[('حكومية', 'حكومية'), ('أهلية', 'أهلية')], default='حكومية', max_length=20, verbose_name='نوع الجامعة'),
        ),
    ]
