# Generated by Django 5.2.10 on 2026-03-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0013_university_university_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='university',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='موقع الجامعة'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_type',
            field=models.CharField(default='حكومية', max_length=20),
        ),
    ]
