# Generated by Django 5.2.10 on 2026-03-12 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0014_alter_application_options_alter_choice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={},
        ),
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
        migrations.AlterField(
            model_name='application',
            name='accepted_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addmission_app.program', verbose_name='القبول النهائي'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('قيد المعالجة', 'قيد المعالجة'), ('مقبول', 'مقبول'), ('مرفوض', 'مرفوض')], default='قيد المعالجة', max_length=20, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='addmission_app.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='addmission_app.application'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='priority',
            field=models.IntegerField(verbose_name='الرغبة رقم'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addmission_app.program', verbose_name='التخصص'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم التخصص/الكلية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='field_of_study',
            field=models.CharField(default=22, max_length=100, verbose_name='المسار الدراسي'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='form_number',
            field=models.CharField(max_length=20, unique=True, verbose_name='رقم الاستمارة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage',
            field=models.FloatField(verbose_name='النسبة المئوية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ولاية السكن'),
        ),
        migrations.AlterField(
            model_name='student',
            name='seat_number',
            field=models.CharField(max_length=50, verbose_name='رقم الجلوس'),
        ),
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الموقع التفصيلي'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='اسم الجامعة'),
        ),
        migrations.AlterField(
            model_name='university',
            name='region',
            field=models.CharField(max_length=100, verbose_name='المنطقة/الولاية'),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_type',
            field=models.CharField(choices=[('حكومية', 'حكومية'), ('خاصة', 'خاصة')], default='حكومية', max_length=20, verbose_name='نوع الجامعة'),
        ),
    ]
