# Generated by Django 5.2.10 on 2026-03-12 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0015_alter_program_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='accepted_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addmission_app.program'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('قيد المعالجة', 'قيد المعالجة'), ('مقبول', 'مقبول'), ('مرفوض', 'مرفوض')], default='قيد المعالجة', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='addmission_app.student'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='priority',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='choice',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addmission_app.program'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم التخصص'),
        ),
        migrations.AlterField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='addmission_app.university'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='field_of_study',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='form_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='seat_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_type',
            field=models.CharField(choices=[('حكومية', 'حكومية'), ('خاصة', 'خاصة')], default='حكومية', max_length=20),
        ),
    ]
