# Generated by Django 5.2.10 on 2026-03-15 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0016_alter_application_accepted_program_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'تخصص', 'verbose_name_plural': 'التخصصات'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'طالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'جامعة', 'verbose_name_plural': 'الجامعات'},
        ),
        migrations.RemoveField(
            model_name='student',
            name='region',
        ),
        migrations.RemoveField(
            model_name='university',
            name='location',
        ),
        migrations.AddField(
            model_name='choice',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبول'), ('not accepted', 'لم يتم قبولك')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='accepted_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addmission_app.program', verbose_name='الرغبة المقبول بها'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التقديم'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('يتم المراجعة', 'يتم المراجعة'), ('تم القبول', 'تم القبول'), ('مرفوض', 'مرفوض')], default='يتم المراجعة', max_length=50, verbose_name='حالة الطلب'),
        ),
        migrations.AlterField(
            model_name='application',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='addmission_app.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='addmission_app.application', verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='priority',
            field=models.PositiveIntegerField(verbose_name='ترتيب الرغبة'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addmission_app.program', verbose_name='التخصص المختار'),
        ),
        migrations.AlterField(
            model_name='program',
            name='university',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='addmission_app.university', verbose_name='الجامعة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='student',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المساق'),
        ),
        migrations.AlterField(
            model_name='student',
            name='form_number',
            field=models.CharField(editable=False, max_length=20, unique=True, verbose_name='رقم الاستمارة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم الطالب'),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage',
            field=models.FloatField(default=0.0, verbose_name='النسبة المئوية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='student',
            name='seat_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='رقم الجلوس'),
        ),
        migrations.AlterField(
            model_name='university',
            name='university_type',
            field=models.CharField(choices=[('حكومية', 'حكومية'), ('أهلية', 'خاصة')], default='حكومية', max_length=20, verbose_name='نوع الجامعة'),
        ),
    ]
