# Generated by Django 5.2.10 on 2026-03-15 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0017_alter_program_options_alter_student_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
