# Generated by Django 5.2.10 on 2026-03-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0018_delete_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='choices_json',
            field=models.TextField(blank=True, default='[]', null=True),
        ),
    ]
