# Generated by Django 5.2.10 on 2026-03-15 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0019_application_choices_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='choices_json',
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='النوع'),
        ),
        migrations.AddField(
            model_name='student',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المنطقة'),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(verbose_name='ترتيب الرغبة')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='addmission_app.application', verbose_name='الطلب')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='addmission_app.program', verbose_name='التخصص المختار')),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
    ]
