# Generated by Django 5.2.10 on 2026-03-15 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0020_remove_application_choices_json_student_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='region',
        ),
    ]
