# Generated by Django 5.2.10 on 2026-03-15 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0021_remove_student_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='gender',
        ),
    ]
