# Generated by Django 5.2.10 on 2026-03-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0023_alter_choice_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='choices_json',
            field=models.TextField(default='[]', verbose_name='الرغبات المسجلة'),
        ),
    ]
