# Generated by Django 5.2.10 on 2026-03-16 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0026_alter_choice_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addmission_app.program'),
        ),
    ]
