# Generated by Django 5.2.10 on 2026-03-16 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0027_alter_choice_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='addmission_app.program', verbose_name='التخصص المختار'),
        ),
    ]
