# Generated by Django 5.2.10 on 2026-03-16 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0028_alter_choice_program'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'طلب تقديم', 'verbose_name_plural': 'طلبات التقديم'},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={},
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.AlterField(
            model_name='choice',
            name='priority',
            field=models.IntegerField(verbose_name='الأولوية'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='addmission_app.program', verbose_name='البرنامج'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم التخصص/الكلية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='field_of_study',
            field=models.CharField(max_length=50, verbose_name='المسار'),
        ),
        migrations.AlterField(
            model_name='student',
            name='form_number',
            field=models.CharField(editable=False, max_length=8, unique=True, verbose_name='رقم الاستمارة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=200, verbose_name='اسم الطالب رباعي'),
        ),
        migrations.AlterField(
            model_name='student',
            name='percentage',
            field=models.FloatField(verbose_name='النسبة المئوية'),
        ),
        migrations.AlterField(
            model_name='student',
            name='seat_number',
            field=models.CharField(max_length=20, verbose_name='رقم الجلوس'),
        ),
    ]
