# Generated by Django 5.2.10 on 2026-03-16 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0029_alter_application_options_alter_choice_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'verbose_name': 'رغبة', 'verbose_name_plural': 'الرغبات'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_choices', to='addmission_app.program', verbose_name='البرنامج'),
        ),
    ]
