# Generated by Django 5.2.10 on 2026-03-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0030_alter_choice_options_alter_choice_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='is_matched',
            field=models.BooleanField(default=False),
        ),
    ]
