# Generated by Django 5.2.10 on 2026-04-28 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addmission_app', '0031_choice_is_matched'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email_address',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='رقم الهاتف'),
        ),
    ]
